"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent


def get_env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


DEBUG = get_env_bool('DJANGO_DEBUG', default=True)
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'dev-secret-key-change-me'
    else:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set in production.')

ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    SECURE_SSL_REDIRECT = get_env_bool('DJANGO_SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = get_env_bool('DJANGO_SESSION_COOKIE_SECURE', default=True)
    CSRF_COOKIE_SECURE = get_env_bool('DJANGO_CSRF_COOKIE_SECURE', default=True)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


def _split_csv(value: str | None) -> list[str]:
    if not value:
        return []
    return [part.strip() for part in value.split(',') if part.strip()]


# LLM / AI configuration: the active model comes from .env LLM_MODEL.
LLM_PROVIDER = os.environ.get('LLM_PROVIDER', 'bedrock').strip()
LLM_DEFAULT_MODEL = (os.environ.get('LLM_MODEL') or '').strip()
if not LLM_DEFAULT_MODEL:
    raise ImproperlyConfigured('LLM_MODEL must be set in .env.')

LLM_MODELS = _split_csv(os.environ.get('LLM_MODELS'))
if LLM_DEFAULT_MODEL not in LLM_MODELS:
    LLM_MODELS.insert(0, LLM_DEFAULT_MODEL)

LLM_CONFIG = {
    'provider': LLM_PROVIDER,
    'default_model': LLM_DEFAULT_MODEL,
    'models': LLM_MODELS,
    'region': os.environ.get('AWS_REGION') or os.environ.get('AWS_DEFAULT_REGION') or 'us-east-1',
    'access_key_id': os.environ.get('AWS_ACCESS_KEY_ID') or os.environ.get('BEDROCK_ACCESS_KEY_ID') or '',
    'secret_access_key': os.environ.get('AWS_SECRET_ACCESS_KEY') or os.environ.get('BEDROCK_SECRET_ACCESS_KEY') or '',
    'session_token': os.environ.get('AWS_SESSION_TOKEN') or os.environ.get('BEDROCK_SESSION_TOKEN') or '',
    'bearer_token': os.environ.get('AWS_BEARER_TOKEN_BEDROCK') or '',
    'base_url': os.environ.get('OPENAI_BASE_URL') or '',
}

# Unit tests must be deterministic and must not accidentally call paid/live AWS
# services just because a developer has credentials exported in the shell. The
# legacy Bedrock integration test is therefore opt-in. Its skip decorator checks
# AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY directly, so hide those variables only
# inside the Django test process unless live integration testing was requested.
TESTING = 'test' in sys.argv
RUN_BEDROCK_INTEGRATION_TESTS = get_env_bool('RUN_BEDROCK_INTEGRATION_TESTS', default=False)
if TESTING and not RUN_BEDROCK_INTEGRATION_TESTS:
    os.environ.pop('AWS_ACCESS_KEY_ID', None)
    os.environ.pop('AWS_SECRET_ACCESS_KEY', None)
    os.environ.pop('AWS_SESSION_TOKEN', None)
    os.environ.pop('AWS_BEARER_TOKEN_BEDROCK', None)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
STATIC_URL = 'static/'

DEFAULT_SEARCH_COUNTRY = os.environ.get('DEFAULT_SEARCH_COUNTRY', 'RDC')
LOCAL_SEARCH_DOMAINS = _split_csv(os.environ.get('LOCAL_SEARCH_DOMAINS')) or ['drcmart.com', 'mobile-rdc.com']

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
