# Generated by Django 6.1.1 on 2026-09-07 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku_or_ean', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=150)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('image_url', models.URLField(blank=True, default='', max_length=2048)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='tracker_pro_name_92bcf1_idx'), models.Index(fields=['sku_or_ean'], name='tracker_pro_sku_or__1f6053_idx')],
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='tracker_ret_name_98d9ad_idx'), models.Index(fields=['base_url'], name='tracker_ret_base_ur_f86ae1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('normalized_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('normalized_currency', models.CharField(default='USD', max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='tracker.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.retailer')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=10)),
                ('normalized_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('normalized_currency', models.CharField(default='USD', max_length=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracker.pricelisting')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['listing', 'recorded_at'], name='tracker_pri_listing_f97029_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pricelisting',
            index=models.Index(fields=['product', 'retailer', 'price'], name='tracker_pri_product_687ffd_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricelisting',
            constraint=models.UniqueConstraint(fields=('product', 'retailer', 'url'), name='unique_listing_per_product_retailer_url'),
        ),
    ]
