# Generated by Django 6.1.1 on 2026-09-04 16:13

from django.db import migrations, models


def deduplicate_price_listings(apps, schema_editor):
    PriceListing = apps.get_model('tracker', 'PriceListing')
    duplicate_keys = (
        PriceListing.objects.values('product_id', 'retailer_id', 'url')
        .annotate(count=models.Count('id'))
        .filter(count__gt=1)
    )

    for duplicate_key in duplicate_keys:
        rows = list(
            PriceListing.objects.filter(
                product_id=duplicate_key['product_id'],
                retailer_id=duplicate_key['retailer_id'],
                url=duplicate_key['url'],
            ).order_by('price', 'id')
        )
        for row in rows[1:]:
            row.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='base_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='pricelisting',
            index=models.Index(fields=['product', 'retailer', 'price'], name='tracker_pri_product_687ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='tracker_pro_name_92bcf1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku_or_ean'], name='tracker_pro_sku_or__1f6053_idx'),
        ),
        migrations.AddIndex(
            model_name='retailer',
            index=models.Index(fields=['name'], name='tracker_ret_name_98d9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='retailer',
            index=models.Index(fields=['base_url'], name='tracker_ret_base_ur_f86ae1_idx'),
        ),
        migrations.RunPython(deduplicate_price_listings, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='pricelisting',
            constraint=models.UniqueConstraint(fields=('product', 'retailer', 'url'), name='unique_listing_per_product_retailer_url'),
        ),
    ]
