# Generated by Django 6.1.2 on 2026-10-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_offerboostrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
    ]
