# Generated by Django 6.1.2 on 2026-10-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_individual_publishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermedia',
            name='optimized_file',
            field=models.FileField(blank=True, upload_to='offers/optimized/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='offermedia',
            name='thumbnail_file',
            field=models.FileField(blank=True, upload_to='offers/thumbnails/%Y/%m/'),
        ),
    ]
