# Generated by Django 6.1.2 on 2026-10-09 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_offer_image_renditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Utilisez un code de trois lettres majuscules, par exemple CDF.')], verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='Symbole')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible à la publication')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='La première devise active sert de choix par défaut si celle du pays est indisponible.', verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Devise (configuration)',
                'verbose_name_plural': 'Devises (configuration)',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
